name: check
on:
  push
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get buildTools"
        uses: ModelingValueGroup/buildTools@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "(re)generate some files"
        run:  |
          . <(java -jar buildTools.jar)
          correctEols
          correctHeaders header

      - name: "push changes back to github"
        run:  |
          git ls-files --deleted --modified --others --exclude-standard || :
          if [[ "$(git ls-files --deleted --modified --others --exclude-standard)" ]]; then
            echo "changes need to be pushed back to github"

            echo "::group::git commit and push"
              git config user.email "automation@modelingvalue.com"
              git config user.name "$GITHUB_ACTOR"
              git add .
              git commit -m "adjusted files [by github actions]"
              git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
            echo "::endgroup::"

          else
            echo "no changes need to be pushed back to github"
          fi
